# Generated by Django 4.2.3 on 2023-07-12 07:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Audio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('file', models.FileField(upload_to='audios/')),
                ('language', models.CharField(max_length=50)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('url', models.URLField()),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PDF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('file', models.FileField(upload_to='pdfs/')),
                ('language', models.CharField(max_length=50)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('file', models.FileField(upload_to='videos/')),
                ('language', models.CharField(max_length=50)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TranslatedVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('translated_file', models.FileField(upload_to='translated_videos/')),
                ('translated_language', models.CharField(max_length=50)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Translatorapi.video')),
            ],
        ),
        migrations.CreateModel(
            name='TranslatedPDF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('translated_file', models.FileField(upload_to='translated_pdfs/')),
                ('translated_language', models.CharField(max_length=50)),
                ('pdf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Translatorapi.pdf')),
            ],
        ),
        migrations.CreateModel(
            name='TranslatedAudio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('translated_file', models.FileField(upload_to='translated_audios/')),
                ('translated_language', models.CharField(max_length=50)),
                ('audio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Translatorapi.audio')),
            ],
        ),
        migrations.CreateModel(
            name='TransaltedLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('translated_file', models.FileField(upload_to='translated_links/')),
                ('translated_language', models.CharField(max_length=50)),
                ('link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Translatorapi.link')),
            ],
        ),
    ]
