# Generated by Django 4.2.3 on 2023-07-12 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Translatorapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='language',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
