# Generated by Django 4.2.3 on 2023-07-12 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Translatorapi', '0002_alter_video_language_alter_video_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='file',
            new_name='video_file',
        ),
    ]
