# Generated by Django 4.2.3 on 2023-07-13 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Translatorapi', '0003_rename_file_video_video_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audio',
            name='language',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
