# Generated by Django 4.2.3 on 2023-07-13 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Translatorapi', '0004_alter_audio_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdf',
            name='language',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
