# Generated by Django 4.2.3 on 2023-07-14 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Translatorapi', '0005_alter_pdf_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audio',
            name='file',
            field=models.FileField(upload_to='uploadedaudios/'),
        ),
        migrations.AlterField(
            model_name='pdf',
            name='file',
            field=models.FileField(upload_to='uploadedpdfs/'),
        ),
        migrations.AlterField(
            model_name='video',
            name='video_file',
            field=models.FileField(upload_to='uploadedvideos/'),
        ),
    ]
